In [1]:
import numpy as np
import ipyparallel as ipp
%matplotlib inline

In [2]:
c= ipp.Client()
c.ids

[0, 1, 2, 3]

In [31]:
dview = c[:]

In [6]:
c[:].apply_sync(lambda: "Hola clase MCA")

['Hola clase MCA', 'Hola clase MCA', 'Hola clase MCA', 'Hola clase MCA']

In [8]:
c[0].map_sync(lambda x,y,z: x+y+z, range(10), range(10),range(10) ) #proceso con un solo motor

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27]

In [9]:
c[:].map_sync(lambda x,y,z: x+y+z, range(10), range(10),range(10))#proceso con todos los motores, map distribuye y da un resultado

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27]

In [10]:
c[:].apply_sync(lambda x,y,z: x+y+z, range(10), range(10),range(10))#el proceso se hace por cada motor

[[0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9],
 [0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9],
 [0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9],
 [0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9]]

In [18]:
x=2**13
np.arange(int(x**0.5)+1)[2:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90])

In [21]:
%%timeit
x=2**13
for i in np.arange(int(x**0.5)+1)[2:]:
    x%i 

10000 loops, best of 3: 25.9 µs per loop


In [ ]:
%%timeit
x=2**13 #cambiar exponente y hacer una gráfica con los tiempos obtenidos con cada exponente
for i in np.arange(int(x**0.5)+1)[2:]:
    x%i 

In [23]:
PrimeQ = lambda x: all(x % i != 0 for i in range(int(x**0.5)+1)[2:]) and x>1

In [35]:
def PrimeQA(x):
    import numpy as np
    return all(x % i for i in np.arange(int(x**0.5)+1)[2:])        

In [36]:
PrimeQA(2**7)

False

In [37]:
dview.apply_sync(PrimeQA, 2**7)

[False, False, False, False]

In [38]:
2**np.arange(7)

array([ 1,  2,  4,  8, 16, 32, 64])

In [40]:
%timeit dview.map_sync(PrimeQA, 2**np.arange(25))

10 loops, best of 3: 52.8 ms per loop


In [42]:
%%timeit
for i in 2**np.arange(25):
    x%i

The slowest run took 10.69 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 15.3 µs per loop


In [48]:
np.array([x % i for i in np.arange(np.int(x**0.5)+1)[2:]])

array([ 0,  2,  0,  2,  2,  2,  0,  2,  2,  8,  8,  2,  2,  2,  0, 15,  2,
        3, 12,  2,  8,  4,  8, 17,  2, 11, 16, 14,  2,  8,  0,  8, 32,  2,
       20, 15, 22,  2, 32, 33,  2, 22,  8,  2,  4, 14, 32,  9, 42, 32, 28,
       30, 38, 52, 16, 41, 14, 50, 32, 18,  8,  2,  0,  2,  8, 18, 32, 50,
        2, 27, 56, 16, 52, 17, 60, 30,  2, 55, 32, 11, 74, 58, 44, 32, 22,
       14,  8,  4,  2])

In [49]:
def PrimeQB(x):
    import numpy as np
    return np.all(np.array([x % i for i in np.arange(np.int(x**0.5)+1)[2:]]))    

In [50]:
%timeit dview.map_sync(PrimeQB, 2**np.arange(25))

10 loops, best of 3: 56.3 ms per loop


In [51]:
np.mod(24,12)

0

In [52]:
np.arange(24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [53]:
np.mod(np.arange(24),12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,
        5,  6,  7,  8,  9, 10, 11])

In [54]:
np.array([hora % 12 for hora in np.arange(24)])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,
        5,  6,  7,  8,  9, 10, 11])

Tarea hacer uso de map_sync, reconstruir la implementación

In [55]:
for med in np.arange(12,20):
    print np.mod(np.arange(24),med) #Tarea hacer uso de map_sync, reconstruir la implementación

[ 0  1  2  3  4  5  6  7  8  9 10 11  0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12  0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13  0  1  2  3  4  5  6  7  8  9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14  0  1  2  3  4  5  6  7  8]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15  0  1  2  3  4  5  6  7]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16  0  1  2  3  4  5  6]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17  0  1  2  3  4  5]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18  0  1  2  3  4]


In [56]:
def PrimeQC(x):
    import numpy as np
    lista = np.arange(np.int(x**0.5)+1)[2:]
    residuos = np.mod(x,lista)
    return np.all(residuos) 

In [57]:
dview.map_sync(PrimeQC, 2**np.arange(10))

[True, True, False, False, False, False, False, False, False, False]

In [58]:
dview.map_sync(PrimeQB, 2**np.arange(10))

[True, True, False, False, False, False, False, False, False, False]

In [59]:
dview.map_sync(PrimeQA, 2**np.arange(10))

[True, True, False, False, False, False, False, False, False, False]

Generar los gráficos comparando tiempos de 2 a 25

In [60]:
%timeit dview.map_sync(PrimeQC, 2**np.arange(10))

10 loops, best of 3: 53 ms per loop


In [61]:
%timeit dview.map_sync(PrimeQB, 2**np.arange(10))

10 loops, best of 3: 54.6 ms per loop


In [62]:
%timeit dview.map_sync(PrimeQA, 2**np.arange(10))

10 loops, best of 3: 52.3 ms per loop


Tarea 1 crear gráfica de tiempos de acuerdo al exponente. llegar hasta 25
for i in 2**np.arange(25):
    x%i
    
Tarea 2 crear gráfica de tiempos de acuerdo al exponente. llegar hasta 25, comparando PrimeQA, PrimeQB, PrimeQC
investigar cómo guardar el tiempo que devuelve %timeit en una variable
identificarn cómo reducir el tiempo

Tarea 3 hacer uso de map_sync, reconstruir la implementación
for med in np.arange(12,20):
    print np.mod(np.arange(24),med)
    